// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUkfMUa3FTNgdddkhRobcCKGvZBOOiz5I',
    appId: '1:1074191505379:web:ce5f62f2f497a4627b72d6',
    messagingSenderId: '1074191505379',
    projectId: 'sendlog-10ddf',
    authDomain: 'sendlog-10ddf.firebaseapp.com',
    storageBucket: 'sendlog-10ddf.firebasestorage.app',
    measurementId: 'G-GJWG4DLGLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJhPm5FKFmZozkMIPTCNTyBbhisY-frOI',
    appId: '1:1074191505379:android:3b5adaa642283bdf7b72d6',
    messagingSenderId: '1074191505379',
    projectId: 'sendlog-10ddf',
    storageBucket: 'sendlog-10ddf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkOgJdBCSGAGnCqwaA33NR78hEpxxY9MI',
    appId: '1:1074191505379:ios:549c9f3ceb9922f37b72d6',
    messagingSenderId: '1074191505379',
    projectId: 'sendlog-10ddf',
    storageBucket: 'sendlog-10ddf.firebasestorage.app',
    iosBundleId: 'com.example.sendLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkOgJdBCSGAGnCqwaA33NR78hEpxxY9MI',
    appId: '1:1074191505379:ios:549c9f3ceb9922f37b72d6',
    messagingSenderId: '1074191505379',
    projectId: 'sendlog-10ddf',
    storageBucket: 'sendlog-10ddf.firebasestorage.app',
    iosBundleId: 'com.example.sendLog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUkfMUa3FTNgdddkhRobcCKGvZBOOiz5I',
    appId: '1:1074191505379:web:cc4cdd22ac1324737b72d6',
    messagingSenderId: '1074191505379',
    projectId: 'sendlog-10ddf',
    authDomain: 'sendlog-10ddf.firebaseapp.com',
    storageBucket: 'sendlog-10ddf.firebasestorage.app',
    measurementId: 'G-0BPRM0JQSY',
  );
}
